const People = [
    {
      userId: "rirani",
      jobTitleName: "Developer",
      firstName: "Romin",
      lastName: "Irani",
      preferredFullName: "Romin Irani",
      employeeCode: "E1",
      region: "CA",
      phoneNumber: "408-1234567",
      emailAddress: "romin.k.irani@gmail.com",
      isActive: true
    },
    {
      userId: "irani",
      jobTitleName: "Developer",
      firstName: "Neil",
      lastName: "Irani",
      preferredFullName: "Neil Irani",
      employeeCode: "E2",
      region: "CA",
      phoneNumber: "408-1111111",
      emailAddress: "neilrirani@gmail.com",
      isActive: false
    },
    {
      userId: "hanks",
      jobTitleName: "Program Directory",
      firstName: "Tom",
      lastName: "Hanks",
      preferredFullName: "Tom Hanks",
      employeeCode: "E3",
      region: "CA",
      phoneNumber: "408-2222222",
      emailAddress: "tomhanks@gmail.com",
      isActive: true
    },
    {
      userId: "jaugustus0",
      jobTitleName: "Information Systems Manager",
      firstName: "Judah",
      lastName: "Augustus",
      preferredFullName: "Judah Augustus",
      employeeCode: "169.126.8.71",
      region: "PT",
      phoneNumber: "402-212-2307",
      emailAddress: "jaugustus0@upenn.edu",
      isActive: false
    },
    {
      userId: "bmyott1",
      jobTitleName: "Web Developer I",
      firstName: "Becky",
      lastName: "Myott",
      preferredFullName: "Becky Myott",
      employeeCode: "68.72.53.223",
      region: "ID",
      phoneNumber: "315-695-2264",
      emailAddress: "bmyott1@patch.com",
      isActive: false
    },
    {
      userId: "pbikker2",
      jobTitleName: "Biostatistician I",
      firstName: "Parry",
      lastName: "Bikker",
      preferredFullName: "Parry Bikker",
      employeeCode: "227.219.98.24",
      region: "SE",
      phoneNumber: "330-364-8339",
      emailAddress: "pbikker2@cornell.edu",
      isActive: false
    },
    {
      userId: "acrompton3",
      jobTitleName: "Senior Cost Accountant",
      firstName: "Abdul",
      lastName: "Crompton",
      preferredFullName: "Abdul Crompton",
      employeeCode: "148.201.180.216",
      region: "CN",
      phoneNumber: "633-686-9856",
      emailAddress: "acrompton3@time.com",
      isActive: false
    },
    {
      userId: "gbradtke4",
      jobTitleName: "Account Representative II",
      firstName: "Galvan",
      lastName: "Bradtke",
      preferredFullName: "Galvan Bradtke",
      employeeCode: "55.208.122.44",
      region: "CN",
      phoneNumber: "899-712-5659",
      emailAddress: "gbradtke4@oaic.gov.au",
      isActive: true
    },
    {
      userId: "ebernaciak5",
      jobTitleName: "VP Sales",
      firstName: "Elvyn",
      lastName: "Bernaciak",
      preferredFullName: "Elvyn Bernaciak",
      employeeCode: "13.207.55.28",
      region: "CN",
      phoneNumber: "377-879-9940",
      emailAddress: "ebernaciak5@yahoo.co.jp",
      isActive: true
    },
    {
      userId: "aklewi6",
      jobTitleName: "Editor",
      firstName: "Audrie",
      lastName: "Klewi",
      preferredFullName: "Audrie Klewi",
      employeeCode: "20.157.61.165",
      region: "CN",
      phoneNumber: "182-976-7139",
      emailAddress: "aklewi6@constantcontact.com",
      isActive: false
    },
    {
      userId: "smcclosh7",
      jobTitleName: "Systems Administrator I",
      firstName: "Sibeal",
      lastName: "McClosh",
      preferredFullName: "Sibeal McClosh",
      employeeCode: "59.37.11.68",
      region: "PT",
      phoneNumber: "343-924-3541",
      emailAddress: "smcclosh7@nymag.com",
      isActive: false
    },
    {
      userId: "lbillin8",
      jobTitleName: "Legal Assistant",
      firstName: "Lani",
      lastName: "Billin",
      preferredFullName: "Lani Billin",
      employeeCode: "0.44.147.210",
      region: "RU",
      phoneNumber: "796-397-4655",
      emailAddress: "lbillin8@people.com.cn",
      isActive: true
    },
    {
      userId: "dwillcock9",
      jobTitleName: "Programmer IV",
      firstName: "Derby",
      lastName: "Willcock",
      preferredFullName: "Derby Willcock",
      employeeCode: "165.218.38.131",
      region: "ID",
      phoneNumber: "247-381-5026",
      emailAddress: "dwillcock9@moonfruit.com",
      isActive: true
    }
  ];
  
  export default People;